%%% Generate PAR/REC files for recons
%% Choose recons
recons = { ...
    struct( ...
        acq = "2025-01-01_HV01_CMRA", ...
        recon_name = "2025-01-01_test", ...
        dcm_name = "HB1_refpos04", ...
        output_prefix = "HV01_test" ...
    ), ...
    struct( ...
        acq = "2025-01-01_HV01_CMRA", ...
        recon_name = "2025-01-01_test2", ...
        dcm_name = "HB1_refpos04", ...
        output_prefix = "HV01_test2" ...
    ), ...
};

%% Iterate over recons
for i_recon = 1:numel(recons)
    config = recons{i_recon};

    % Prepare input
    recon_folder = fullfile(getenv("WORKSPACE"), "acquisitions", config.acq, "recons", config.recon_name);
    input_fname = fullfile(recon_folder, "dcm", sprintf("%s.dcm", config.dcm_name));

    % Prepare output folder
    output_folder = fullfile(recon_folder, "par_rec");
    if ~exist(output_folder, "dir"), mkdir(output_folder); end
    output_basename = fullfile(output_folder, sprintf("%s_%s", config.output_prefix, config.dcm_name));

    % Create par/rec pair
    dicom2parrec(input_fname, output_basename, struct(verbose=true));
end

