%%% Generate NII files for recons
%% Choose recons
recons = { ...
    struct( ...
        acq = "2025-01-01_HV01_CMRA", ...
        recon_name = "2025-01-01_test2", ...
        contrast = "HB1" ...
    ), ...
    struct( ...
        acq = "2025-01-01_HV01_CMRA", ...
        recon_name = "2025-01-01_test2", ...
        contrast = "HB1" ...
    ), ...
};

%% Iterate over recons
for i_recon = 1:numel(recons)
    config = recons{i_recon};
    config.acq = fullfile(getenv("WORKSPACE"), "acquisitions", config.acq);

    % Load data
    img = load_final_recons(config.acq, config.recon_name, config.contrast);
    img = concat_cell_to_array(img);

    % Prepare output folder
    output_folder = fullfile(config.acq, "recons", config.recon_name, "nii");
    if ~exist(output_folder, "dir"), mkdir(output_folder); end
    output_name = fullfile(output_folder, "rr.nii");

    % Save NII
    resolution = [1.5 1.5 1.5]; % TODO(pdpino): get resolution from dcm
    save_nii(make_nii(single(img), resolution), output_name);
    fprintf("NII saved to %s\n", output_name);
end
