function path_to_twix = find_twix_file(pattern)

    % for matching behaviour, see documentation for dir

    if extractAfter(pattern, strlength(pattern) - 4) ~= ".dat"
        pattern = append(pattern, ".dat");
    end

    match = dir(pattern);

    if isempty(match)
        error("no twix file matched the pattern")
    end

    if numel(match) > 1
        dialogbox = dialog( ...
            "Position", [300 300 250 150], ...
            "CloseRequestFcn", @select_twix ...
        );

        uicontrol( ...
            "Parent", dialogbox, ...
            "Style", "text", ...
            "Position", [20 120 210 20], ...
            "String", "more than one twix file matched the pattern:" ...
        )

        match_list = uicontrol( ...
            "Parent", dialogbox, ...
            "Position", [20 50 210 70], ...
            "Style", "listbox", ...
            "String", {match.name}...
        );

        uicontrol( ...
            "Parent", dialogbox, ...
            "Style", "pushbutton", ...
            "Position", [20 20 60 20], ...
            "String", "continue", ...
            "Callback", @select_twix ...
        )

        waitfor(dialogbox)
        
    end

    path_to_twix = fullfile(match.folder, match.name);
    
    fprintf("selected file is: %s\n", path_to_twix)

    function select_twix(~, ~)
        match = match(match_list.Value);
        delete(dialogbox)
    end

end

