function image = non_rigid_it_SENSE(k_space, binned_sampling_masks, displacement_fields, csm)

    n_iter = 4;
    verbose = false;

    operator = Cruz_E_3D_CART_BATCH( ...
        displacement_fields, ...
        binned_sampling_masks, ...
        csm.coil_sensitivity_maps, ...
        size(csm.coil_sensitivity_maps,4), ...
        size(k_space, 1:3), ...
        size(k_space), ...
        csm.coil_sensitivity_sum ...
    );

    result = Cart_itSENSE(k_space, operator, n_iter, verbose);
    image = flip(flip(flip(result, 1), 2), 3); % ./ csm.coil_sensitivity_sum ??

end