function image = non_rigid_it_SENSE(k_space, binned_sampling_masks, interp_matrices, csm)
    n_iter = 4;
    verbose = false;

    operator = Cruz_E_3D_CART_BATCH( ...
        interp_matrices, ...
        binned_sampling_masks, ...
        csm.coil_sensitivity_maps, ...
        size(csm.coil_sensitivity_maps,4), ...
        size(k_space, 1:3), ...
        size(k_space) ...
    );

    result = Cart_itSENSE(k_space, operator, n_iter, verbose);
    image = flip(flip(flip(result, 1), 2), 3);
end
