function csm = get_csm(data, algorithm_name, selected,params)
%GET_CSM Wrapper to call csm calculation function

    k_space_for_csm = data.k_spaces{selected.echo,selected.set,selected.repetition};

    if algorithm_name == "scanner"
        % No need to filter kspace if loading CSMs from a file
        filtered_k_space = k_space_for_csm;
    else
        filter_dims = size(k_space_for_csm, 1:3);
        filter_std = 10;
        filtered_k_space = k_space_for_csm .* fspecial3('gaussian', filter_dims, filter_std);
    end
    switch lower(algorithm_name)
      case "walsh"
          prost_params = struct( ...
            sig = 0.055, ...
            patch_sz = 5, ...
            max_patch = 20, ...
            win = 20, ...
            offset = 4, ...
            debug = 0, ...
            recon_mode = 6, ...
            sharpness = 0, ...
            type = 1, ...
            ref_idx = 1);
          image_sample = ktoi(filtered_k_space, 1:3);
          low_image_recon = denoising_HD_PROST(image_sample,prost_params);
          csm = estimate_coil_sensitivity_maps(low_image_recon, algorithm_name,params);
      otherwise
          csm = estimate_coil_sensitivity_maps(filtered_k_space, algorithm_name,params);
    end
end